[package]
name = "lisel"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.28"
nom = "7"
regex = "1.11.2"
tempfile = "3.21.0"
thiserror = "2.0.16"
