[package]
name = "lisel"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
nom = "7"
regex = "1.11.1"
tempfile = "3.14.0"
thiserror = "2.0.9"
