[package]
name = "lisel"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.22"
nom = "7"
regex = "1.10.5"
tempfile = "3.10.1"
thiserror = "1.0.62"
